### ISSUE TITLE
[ISSUE] Incorrect diff detection in `databricks_share` resource

### ISSUE THREAD

**Issue by marekbrysa** [databricks/terraform-provider-databricks#2003]
It seems that the detection of diffs in the `databricks_share` is incorrect. It generates a diff every time I try to apply TF even if the configuration does not change.

### Configuration
```yaml
databricks_share:
      share_to_xxx:
        name: share_to_XXX
        object:
        - data_object_type: TABLE
          name: main.default.XXX1
        - data_object_type: TABLE
          name: main.default.XXX1
```

### Expected Behavior
No diff is found after the first terraform apply.

### Actual Behavior
Diff generated with every apply:
```
# databricks_share.share_to_system_tables will be updated in-place
  ~ resource "databricks_share" "share_to_xxx" {
        created_at = 1676380776020
        created_by = "XXX"
        id         = "share_to_XXX"
        name       = "share_to_XXX"

      - object {
          - added_at         = 1676380776426 -> null
          - added_by         = "XXX" -> null
          - data_object_type = "TABLE" -> null
          - name             = "main.default.XXX1" -> null
          - shared_as        = "default.XXX1" -> null
        }
      - object {
          - added_at         = 1676380776410 -> null
          - added_by         = "XXX" -> null
          - data_object_type = "TABLE" -> null
          - name             = "main.default.XXX2" -> null
          - shared_as        = "default.XXX2" -> null
        }
      + object {
          + added_at         = (known after apply)
          + added_by         = (known after apply)
          + data_object_type = "TABLE"
          + name             = "main.default.XXX1"
          + shared_as        = (known after apply)
        }
      + object {
          + added_at         = (known after apply)
          + added_by         = (known after apply)
          + data_object_type = "TABLE"
          + name             = "main.default.XXX2"
          + shared_as        = (known after apply)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
`terraform apply` twice.

### Terraform and provider versions
1.9.1
### Debug Output
N/A

### Important Factoids
N/A
