### ISSUE TITLE
[ISSUE] Unable to set Azure OIDC authentication when certain env vars are set

### ISSUE THREAD

**Issue by audunsolemdal** [databricks/terraform-provider-databricks#2234]
I am having a hard time using Azure OIDC for the databricks provider together with the env vars ARM_CLIENT_ID and ARM_TENANT_ID being set. If they are unset, I can easily use the content of .databrickscfg just fine. I do however not wish to do that, as I use these env vars for the azurerm and azuread providers for 50+ repos using the workflow templates, and I do not wish to explicitly type down client_id and tenant_id in each of the repos.

I tried various configurations, but it does not seem possible to get OIDC auth for the databricks provider working while these two env vars are set.

### Configuration

github action to fetch databricks token:

```yaml
  steps:
    - uses: Azure/login@v1
      name: Login with federated credentials
      with:
        tenant-id: ${{ inputs.tenant-id }}
        client-id: ${{ inputs.client-id }}
        allow-no-subscriptions: true

    - name: FetchBearerToken
      shell: bash
      id: bearer
      run: |
        DATABRICKS_AAD_TOKEN=`az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | jq -r '.accessToken'`

        echo "[DEFAULT]
        host = ${{ inputs.workspace }}
        token = $DATABRICKS_AAD_TOKEN
        jobs-api-version = 2.1" > ~/.databrickscfg

        cat ~/.databrickscfg
```

```hcl

provider "azurerm" {
  features {}
  subscription_id     = "xxxxx"
  storage_use_azuread = true
  #tenant_id Set as env.var ARM_TENANT_ID in github workflow template
  #client_id = Set as env.var ARM_CLIENT_ID in github workflow template
  #use_oidc = set.as.env var ARM_USE_OIDC in github workflow template
}

provider "databricks" {
  config_file = "~/.databrickscfg"
}


provider "databricks" {
  host        = "https://accounts.azuredatabricks.net"
  account_id  = "xxxx-"
  alias       = "account"
  config_file = "~/.databrickscfg
}

```

### Expected Behavior

Ideally I would like If ARM_USE_OIDC = true, require arm_tenant_id and arm_client_id env vars / inputs being set, and implement authentication in a similar way which azurerm, azuread, azapi provider do this. 

A more quick fix can be for the databricks provider to read the ARM_USE_OIDC env var, which seems to be ignored in the databricks provider, ref. https://registry.terraform.io/providers/databricks/databricks/latest/docs#environment-variables
If = true, allow arm_client_id, arm_tenant_id being set together with reading the .databrickscfg file.

### Actual Behavior

```
Error: validate: more than one authorization method configured: azure and pat. Config: host=https://accounts.azuredatabricks.net/, account_id=xxxx, token=***, config_file=~/.databrickscfg, azure_client_id=yyy azure_tenant_id=xxxxxx. Env: DATABRICKS_TOKEN, ARM_CLIENT_ID, ARM_TENANT_ID
```

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
terraform version: 1.4.5
databricks provider: 1.14.3
