### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by PaulBurridge** [databricks/terraform-provider-databricks#4760]
### Configuration

Note this is from asset bundle configuration, not directly from Terraform

```hcl
  apps:
    reporting_app:
      name: 'reporting-app'
      description: 'Reporting application'
      source_code_path: '../../apps/reporting/'
      user_api_scopes:
        - sql

      resources:
        - name: snapshot_job
          job:
            id: ${resources.jobs.snapshot_by_project.id}
            permission: 'CAN_MANAGE_RUN'
        - name: sql_warehouse
          sql_warehouse:
            id: ${var.warehouse_id}
            permission: 'CAN_USE'
```

**Comment by alexott** [comment]
@pietern DABs related

**Comment by krishnasism** [comment]
Same issue

Databricks App File:
```yaml
resources:
  apps:
    mdm_flask_app:
      name: ${var.mdm_app_name}-${bundle.target}
      description: "Flask app for MDM table management"
      source_code_path: ../mdm-flask-app

      user_api_scopes:
        - sql
```

Error:
```

Error: Provider produced inconsistent result after apply

When applying changes to databricks_app.mdm_flask_app, provider
"provider[\"registry.terraform.io/databricks/databricks\"]" produced an
unexpected new value: .user_api_scopes: was
cty.ListVal([]cty.Value{cty.StringVal("sql")}), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

If I edit manually in the Databricks GUI, the change doesn't persist either. The CLI gives me an error as well, with no message 
```
databricks apps update mdm-flask-app-da-weu-test --json '{"user_api_scopes": ["sql"]}'
Error:
```

Please keep us updated 😺
